from dataclasses import dataclass


# These messages are so wide that they bring the maximum textbox width past 400px.
# But they already have their own hard wraps, so the autosoftwrapping doesn't
# kick in.
# We force the matter, transforming e.g.
#
#   A lodestone token inscribed with the record of
#   a legend athlete. Enemy bullets give a bit
#   more TP.
#
#   A lodestone token inscribed
#   with the record of
#   a legend athlete. Enemy
#   bullets give a bit
#   more TP.
#
# We actually wrap these messages more narrowly than normal because that makes
# them less jagged.
FORCE_WRAP = {
    "scr_armorinfo_slash_scr_armorinfo_gml_539_0",
    "scr_armorinfo_slash_scr_armorinfo_gml_565_0",
    "scr_armorinfo_slash_scr_armorinfo_gml_568_0",
    "scr_text_slash_scr_text_gml_10537_0",
    "scr_weaponinfo_slash_scr_weaponinfo_gml_607_0",
    "scr_armorinfo_slash_scr_armorinfo_gml_705_0",
    "scr_armorinfo_slash_scr_armorinfo_gml_768_0",
    "scr_itemdesc_single_slash_scr_itemdesc_single_gml_9_0",
    "scr_itemdesc_single_slash_scr_itemdesc_single_gml_151_0",
    "scr_text_slash_scr_text_gml_11457_0",
    "scr_weaponinfo_slash_scr_weaponinfo_gml_630_0",
    "scr_weaponinfo_slash_scr_weaponinfo_gml_653_0",
    "scr_weaponinfo_slash_scr_weaponinfo_gml_676_0",
    "scr_weaponinfo_slash_scr_weaponinfo_gml_699_0",
    # This one is funnier not to wrap
    # "scr_keyiteminfo_slash_scr_keyiteminfo_gml_52_0",
}


@dataclass
class Dim:
    width: int
    height: int
    origin_x: int
    origin_y: int


FUNNYTEXT_DIMS = {
    "spr_dw_tv_time_funnytext": Dim(478, 120, 239, 60),
    "spr_funnytext_alligator": Dim(386, 62, 186, 30),
    "spr_funnytext_amazing_01": Dim(409, 123, 204, 61),
    "spr_funnytext_big": Dim(97, 58, 48, 29),
    "spr_funnytext_board": Dim(133, 64, 71, 46),
    "spr_funnytext_bonus_round": Dim(268, 69, 134, 34),
    "spr_funnytext_breaking_news": Dim(305, 71, 153, 55),
    "spr_funnytext_brother": Dim(182, 47, 91, 23),
    "spr_funnytext_challenge": Dim(261, 59, 130, 39),
    "spr_funnytext_city_feet": Dim(313, 61, 156, 30),
    "spr_funnytext_coffee": Dim(334, 28, 154, 10),
    "spr_funnytext_dark_fountain": Dim(440, 81, 220, 40),
    "spr_funnytext_flames": Dim(171, 45, 85, 22),
    "spr_funnytext_free": Dim(37, 28, 18, 14),
    "spr_funnytext_fun_loop": Dim(104, 55, 52, 27),
    "spr_funnytext_fun_o_meter": Dim(248, 52, 124, 26),
    "spr_funnytext_game": Dim(121, 51, 60, 25),
    "spr_funnytext_game_over": Dim(370, 76, 186, 50),
    "spr_funnytext_gentle": Dim(344, 62, 170, 30),
    "spr_funnytext_grand_prize": Dim(296, 55, 148, 27),
    "spr_funnytext_green_room": Dim(311, 66, 158, 34),
    "spr_funnytext_hall_of_fame": Dim(238, 52, 119, 36),
    "spr_funnytext_know_tv": Dim(336, 28, 158, 10),
    "spr_funnytext_love": Dim(124, 58, 62, 29),
    "spr_funnytext_lovely": Dim(143, 55, 71, 27),
    "spr_funnytext_lovers": Dim(151, 40, 75, 20),
    "spr_funnytext_names": Dim(172, 42, 86, 21),
    "spr_funnytext_over": Dim(250, 104, 127, 53),
    "spr_funnytext_over_small": Dim(111, 55, 55, 27),
    "spr_funnytext_physical_challenge": Dim(391, 69, 195, 34),
    "spr_funnytext_physical_challenges": Dim(391, 69, 195, 34),
    "spr_funnytext_prizes": Dim(168, 62, 84, 31),
    "spr_funnytext_quizzes": Dim(159, 52, 79, 26),
    "spr_funnytext_relax": Dim(259, 74, 128, 32),
    "spr_funnytext_resumes": Dim(124, 27, 0, 0),
    "spr_funnytext_rock_concert": Dim(301, 62, 150, 31),
    "spr_funnytext_round_1": Dim(188, 69, 94, 34),
    "spr_funnytext_round": Dim(154, 69, 77, 34),
    "spr_funnytext_rounds": Dim(168, 69, 84, 34),
    "spr_funnytext_special": Dim(110, 69, 55, 34),
    "spr_funnytext_star": Dim(147, 60, 73, 40),
    "spr_funnytext_stars": Dim(173, 60, 86, 40),
    "spr_funnytext_stop": Dim(87, 69, 44, 34),
    "spr_funnytext_susiezilla": Dim(171, 38, 86, 19),
    "spr_funnytext_tan": Dim(458, 28, 220, 12),
    "spr_funnytext_tears": Dim(196, 42, 98, 31),
    "spr_funnytext_toriel": Dim(159, 55, 79, 37),
    "spr_funnytext_tv_time": Dim(192, 68, 91, 34),
    "spr_funnytext_win_big": Dim(261, 125, 130, 62),
    "spr_funnytext_win": Dim(108, 40, 54, 20),
    "spr_funnytext_word": Dim(136, 51, 68, 25),
    "spr_ja_funnytext_alligator": Dim(412, 66, 206, 33),
    "spr_ja_funnytext_amazing_01": Dim(499, 123, 249, 61),
    "spr_ja_funnytext_board": Dim(133, 64, 66, 42),
    "spr_ja_funnytext_brother": Dim(159, 47, 79, 23),
    "spr_ja_funnytext_challenge": Dim(192, 59, 96, 49),
    "spr_ja_funnytext_city_feet": Dim(362, 66, 181, 33),
    "spr_ja_funnytext_coffee": Dim(305, 64, 152, 32),
    "spr_ja_funnytext_daisuki": Dim(126, 58, 63, 29),
    "spr_ja_funnytext_dark_fountain": Dim(181, 81, 90, 40),
    "spr_ja_funnytext_flames": Dim(42, 45, 21, 22),
    "spr_ja_funnytext_fun_loop": Dim(302, 53, 151, 26),
    "spr_ja_funnytext_fun_o_meter": Dim(206, 52, 103, 26),
    "spr_ja_funnytext_gentle": Dim(344, 66, 172, 33),
    "spr_ja_funnytext_grand_prize": Dim(154, 55, 77, 32),
    "spr_ja_funnytext_green_room": Dim(113, 66, 56, 33),
    "spr_ja_funnytext_hall_of_fame": Dim(262, 65, 131, 46),
    "spr_ja_funnytext_know_tv": Dim(352, 68, 176, 34),
    "spr_ja_funnytext_love": Dim(55, 58, 27, 29),
    "spr_ja_funnytext_lovely": Dim(174, 55, 87, 27),
    "spr_ja_funnytext_lovers": Dim(151, 40, 75, 20),
    "spr_ja_funnytext_names": Dim(84, 42, 42, 21),
    "spr_ja_funnytext_physical_challenge": Dim(305, 66, 152, 33),
    "spr_ja_funnytext_prizes": Dim(100, 62, 50, 31),
    "spr_ja_funnytext_quizzes": Dim(107, 52, 53, 26),
    "spr_ja_funnytext_relax": Dim(259, 74, 129, 37),
    "spr_ja_funnytext_rock_concert": Dim(225, 53, 112, 30),
    "spr_ja_funnytext_star": Dim(148, 60, 74, 40),
    "spr_ja_funnytext_stars": Dim(119, 60, 59, 50),
    "spr_ja_funnytext_susiezilla": Dim(136, 52, 68, 26),
    "spr_ja_funnytext_tan": Dim(303, 65, 151, 32),
    "spr_ja_funnytext_tears": Dim(112, 42, 56, 31),
    "spr_ja_funnytext_toriel": Dim(276, 55, 138, 37),
    "spr_ja_funnytext_win_big": Dim(437, 139, 218, 78),
    "spr_ja_funnytext_win": Dim(167, 40, 83, 14),
    "spr_ja_funnytext_word": Dim(232, 38, 116, 19),
}

FUNNYTEXT_WHITE = {
    "spr_funnytext_alligator",
    "spr_funnytext_brother",
    "spr_funnytext_city_feet",
    "spr_funnytext_coffee",
    "spr_funnytext_gentle",
    "spr_funnytext_know_tv",
    "spr_funnytext_relax",
    "spr_funnytext_tan",
    "spr_ja_funnytext_alligator",
    "spr_ja_funnytext_brother",
    "spr_ja_funnytext_city_feet",
    "spr_ja_funnytext_coffee",
    "spr_ja_funnytext_gentle",
    "spr_ja_funnytext_know_tv",
    "spr_ja_funnytext_relax",
    "spr_ja_funnytext_tan",
}

ALT_TEXTS = {
    "spr_dw_tv_time_funnytext": "IT'S!! TV!! TiME!!!",
    "spr_funnytext_alligator": "(Guess your mother's never been\na fan of alligators in bikinis.)",
    "spr_funnytext_amazing_01": "AMAZING",
    "spr_funnytext_big": "BIG",
    "spr_funnytext_board": "BOARD",
    "spr_funnytext_bonus_round": "BONUS ROUND",
    "spr_funnytext_breaking_news": "BREAKING NEWS",
    "spr_funnytext_brother": "BROTHER",
    "spr_funnytext_challenge": "CHALLENGE",
    "spr_funnytext_city_feet": "(But don't ask why the cars\ndon't have feet!)",
    "spr_funnytext_coffee": "(And get me a cup of coffee.)",
    "spr_funnytext_dark_fountain": "DARK FOUNTAIN",
    "spr_funnytext_flames": "FLAMES",
    "spr_funnytext_free": "Free!",
    "spr_funnytext_fun_loop": "FUN",
    "spr_funnytext_fun_o_meter": "FUN-O-METER",
    "spr_funnytext_game": "GAME",
    "spr_funnytext_game_over": "GAME OVER!?",
    "spr_funnytext_gentle": "(Well, okay, you can touch it.\nJust be gentle.)",
    "spr_funnytext_grand_prize": "GRAND PRIZE",
    "spr_funnytext_green_room": "Green Room",
    "spr_funnytext_hall_of_fame": "Hall of Fame",
    "spr_funnytext_know_tv": "(And trust me. I know TV.)",
    "spr_funnytext_love": "LOVE",
    "spr_funnytext_lovely": "Lovely",
    "spr_funnytext_lovers": "LOVERS",
    "spr_funnytext_names": "NAMES",
    "spr_funnytext_over_small": "OVER",
    "spr_funnytext_physical_challenge": "PHYSICAL CHALLENGE",
    "spr_funnytext_physical_challenges": "PHYSICAL CHALLENGES",
    "spr_funnytext_prizes": "PRIZES",
    "spr_funnytext_quizzes": "QUIZZES",
    "spr_funnytext_relax": "Relax and Enjoy...",
    "spr_funnytext_resumes": "Résumés",
    "spr_funnytext_rock_concert": "ROCK CONCERT",
    "spr_funnytext_round": "ROUND",
    "spr_funnytext_round_1": "ROUND 1!",
    "spr_funnytext_rounds": "ROUNDS",
    "spr_funnytext_special": "Special",
    "spr_funnytext_star": "STAR",
    "spr_funnytext_stars": "STARS",
    "spr_funnytext_stop": "STOP",
    "spr_funnytext_susiezilla": "SUSIEZILLA",
    "spr_funnytext_tan": "(Though I would look good with a tan.)",
    "spr_funnytext_tears": "TEARS",
    "spr_funnytext_toriel": "TORIEL",
    "spr_funnytext_tv_time": "TV TiME!",
    "spr_funnytext_win": "WIN!",
    "spr_funnytext_win_big": "*WIN!",
    "spr_funnytext_word": "WORD",
    "spr_ja_funnytext_alligator": "(トリエルママは　ビキニのワニが\nおキライだったのかな！？)",
    "spr_ja_funnytext_amazing_01": "アメ～イジ～ング！",
    "spr_ja_funnytext_board": "PARK",
    "spr_ja_funnytext_brother": "お兄ちゃん",
    "spr_ja_funnytext_challenge": "チャレンジ",
    "spr_ja_funnytext_city_feet": "(クルマに　足がないところは\nツッコミ禁止ですよ～！)",
    "spr_ja_funnytext_coffee": "(ついでに　ワタシに\nコーヒーも　いれてネ♡)",
    "spr_ja_funnytext_daisuki": "大～スキ♥",
    "spr_ja_funnytext_dark_fountain": "闇の泉",
    "spr_ja_funnytext_flames": "炎",
    "spr_ja_funnytext_fun_loop": "AHAHAHAHAHA!!",
    "spr_ja_funnytext_fun_o_meter": "ハピハピメーター",
    "spr_ja_funnytext_gentle": "(だって　チャンネルちゃんは\nそのままで十分　魅力的♡)",
    "spr_ja_funnytext_grand_prize": "優勝賞品",
    "spr_ja_funnytext_green_room": "楽屋",
    "spr_ja_funnytext_hall_of_fame": "殿堂入り",
    "spr_ja_funnytext_know_tv": "(テレビ本人が言うんですから\nまちがいない!)",
    "spr_ja_funnytext_love": "愛",
    "spr_ja_funnytext_lovely": "ラブラブ ラブリ～",
    "spr_ja_funnytext_lovers": "恋人たち",
    "spr_ja_funnytext_names": "名前",
    "spr_ja_funnytext_physical_challenge": "リアルチャレンジ",
    "spr_ja_funnytext_prizes": "賞品",
    "spr_ja_funnytext_quizzes": "クイズ",
    "spr_ja_funnytext_relax": "ゆったりのひととき",
    "spr_ja_funnytext_rock_concert": "ROCK☆LIVE",
    "spr_ja_funnytext_star": "スタア",
    "spr_ja_funnytext_stars": "主役",
    "spr_ja_funnytext_susiezilla": "スージラ",
    "spr_ja_funnytext_tan": "(日焼けしたら　さぞ\nモテモテでSHOWけど!)",
    "spr_ja_funnytext_tears": "ナミダ",
    "spr_ja_funnytext_toriel": "マイスカイ・トリエール",
    "spr_ja_funnytext_win": "CLEAR!",
    "spr_ja_funnytext_win_big": "優勝してね♥",
    "spr_ja_funnytext_word": "ご覧のスポンサー",
}


FUNNYTEXT_SOUNDS = {
    "spr_funnytext_fun_loop": "snd_crowd_cheer_single",
    "spr_funnytext_big": "snd_ftext_bounce",
    "spr_funnytext_physical_challenge": "snd_ftext_bounce",
    "spr_funnytext_physical_challenges": "snd_ftext_bounce",
    "spr_funnytext_board": "snd_ftext_woodblock",
    "spr_funnytext_challenge": "snd_ftext_woodblock",
    "spr_funnytext_bonus_round": "snd_ftext_prize",
    "spr_funnytext_word": "snd_ftext_prize",
    "spr_funnytext_hall_of_fame": "snd_ftext_prize",
    "spr_funnytext_amazing_01": "snd_ftext_prize",
    "spr_funnytext_breaking_news": "snd_whip_crack_only",
    "spr_funnytext_flames": "snd_badexplosion",
    "spr_funnytext_fun_o_meter": "snd_ftext_enter",
    "spr_funnytext_special": "snd_ftext_enter",
    "spr_funnytext_susiezilla": "snd_ftext_susiezilla",
    "spr_funnytext_dark_fountain": "snd_ftext_dark_fountain",
    "spr_funnytext_brother": "snd_ftext_brother",
    "spr_funnytext_grand_prize": "snd_ftext_gunshot",
    "spr_funnytext_prizes": "snd_ftext_gunshot",
    "spr_funnytext_round": "snd_ftext_gunshot",
    "spr_funnytext_round_1": "snd_ftext_gunshot",
    "spr_funnytext_rounds": "snd_ftext_gunshot",
    "spr_funnytext_game_over": "snd_ftext_gunshot",
    "spr_funnytext_game": "snd_ftext_gunshot",
    "spr_funnytext_over": "snd_ftext_gunshot",
    "spr_funnytext_names": "snd_ftext_names",
    "spr_funnytext_toriel": "snd_ftext_toriel",
    "spr_funnytext_green_room": "snd_ftext_vibraphones",
    "spr_funnytext_quizzes": "snd_ftext_vibraphones",
    "spr_funnytext_love": "snd_audience_aww",
    "spr_funnytext_lovely": "snd_audience_aww",
    "spr_funnytext_lovers": "snd_audience_aww",
    "spr_funnytext_star": "snd_sparkle_glock",
    "spr_funnytext_stars": "snd_sparkle_glock",
    "spr_funnytext_stop": "snd_locker",
    "spr_funnytext_tears": "snd_splat",
    "spr_funnytext_win_big": "snd_carhonk",
}


# Missing from the localization sprite map and therefore not found
FUNNYTEXT_SOUNDS_BROKEN = {
    "spr_funnytext_big",
    "spr_funnytext_round",
    "spr_funnytext_round_1",
    "spr_funnytext_rounds",
    "spr_funnytext_game_over",
    "spr_funnytext_game",
    "spr_funnytext_over",
    "spr_funnytext_stop",
}


FUNNYTEXT_SOUND_BROKEN_JA = {
    # Broken because it hardcodes the JP sprite name(?)
    "obj_ch3_GSA04_slash_Step_0_gml_230_0",
    # Present in the EN localization sprite map but not the JA map
    "obj_ch3_GSB03_slash_Step_0_gml_279_0",
    "obj_ch3_GSC05_slash_Step_0_gml_233_0",
}
